---
- name: Install virtualbox dependencies
  yum:
    name:
      - kernel-devel-{{ansible_kernel}}
      - gcc
      - perl
      - bzip2

- name: Mount guest additions iso
  mount: name=/mnt src=/tmp/VBoxGuestAdditions.iso opts=loop,ro fstype=iso9660 state=mounted

- name: Run guest additions installer
  shell: /mnt/VBoxLinuxAdditions.run

- name: Umount guest additions iso
  mount: name=/mnt src=/tmp/VBoxGuestAdditions.iso fstype=loop state=absent

- name: Remove guest additions iso and tmp files
  file: path={{item}} state=absent
  with_items:
    - /tmp/VBoxGuestAdditions.iso
    - /tmp/vboxguest-Module.symvers

- name: Undo yum history
  shell: yum -y history undo last
  args:
    warn: no

- import_tasks: tasks/vagrant_user.yml
